[package]
name = "sbrush"
version = "0.1.0"
edition = "2021"
authors = ["Samuel Goertz <samuel.goertz7@gmail.com>"]

[dependencies]
bytemuck = "1.21.0"
glam = "0.30.0"
pollster = "0.4.0"
wgpu = "24.0.0"
winit = "0.30.9"
